CONNECT TO <DBNAME>;

CREATE BUFFERPOOL USERSBP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL INDXBP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL BLOBBP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL TEMPUSRBP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL TEMPSYSBP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL TEMPUSRBP32 SIZE AUTOMATIC PAGESIZE 32K;
CREATE BUFFERPOOL TEMPSYSBP32 SIZE AUTOMATIC PAGESIZE 32K;
CREATE BUFFERPOOL XML_DATA_BP SIZE AUTOMATIC PAGESIZE 32K;
CREATE BUFFERPOOL XML_LARGE_BP SIZE AUTOMATIC PAGESIZE 32K;
CREATE BUFFERPOOL XML_INDX_BP SIZE AUTOMATIC PAGESIZE 32K;

CREATE BUFFERPOOL ITA_DATA_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL ITA_IX_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL ITD_DATA_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL ITD_IX_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL ITM_DATA_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL ITM_IX_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL ICM_DATA_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL ICM_IX_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL LCK_DATA_BP SIZE AUTOMATIC PAGESIZE 16K;
CREATE BUFFERPOOL LCK_IX_BP SIZE AUTOMATIC PAGESIZE 16K;