CONNECT TO <DBNAME>;

CREATE LARGE TABLESPACE USERS PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL USERSBP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE INDX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL INDXBP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE BLOB_TBL_DATA PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL BLOBBP
FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE XML_DATA PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL XML_DATA_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 100M;

CREATE LARGE TABLESPACE XML_LARGE_DATA PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL XML_LARGE_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 100M;

CREATE LARGE TABLESPACE XML_INDEX PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL XML_INDX_BP
FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 100M;

CREATE LARGE TABLESPACE ITA_DATA PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ITA_DATA_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE ITM_DATA PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ITM_DATA_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE ITD_DATA PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ITD_DATA_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE ICM_DATA PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ICM_DATA_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE LCK_DATA PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL LCK_DATA_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE ITA_IX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ITA_IX_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE ITM_IX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ITM_IX_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE ITD_IX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ITD_IX_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE ICM_IX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL ICM_IX_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE LARGE TABLESPACE LCK_IX PAGESIZE 16K MANAGED BY AUTOMATIC STORAGE
BUFFERPOOL LCK_IX_BP
NO FILE SYSTEM CACHING AUTORESIZE YES INCREASESIZE 1G;

CREATE USER TEMPORARY TABLESPACE TEMP_USER PAGESIZE 16K MANAGED
BY AUTOMATIC STORAGE
BUFFERPOOL TEMPUSRBP;

CREATE SYSTEM TEMPORARY TABLESPACE TEMP_SYSTEM PAGESIZE 16K MANAGED
BY AUTOMATIC STORAGE
BUFFERPOOL TEMPSYSBP;

CREATE USER TEMPORARY TABLESPACE TEMP_USER32 PAGESIZE 32K MANAGED
BY AUTOMATIC STORAGE
BUFFERPOOL TEMPUSRBP32;

CREATE SYSTEM TEMPORARY TABLESPACE TEMP_SYSTEM32 PAGESIZE 32K MANAGED
BY AUTOMATIC STORAGE
BUFFERPOOL TEMPSYSBP32;
