CONNECT TO <DBNAME>;

GRANT DBADM, CREATETAB, BINDADD, CONNECT, CREATE_NOT_FENCED, IMPLICIT_SCHEMA, LOAD ON DATABASE TO USER <DBUSER>;

GRANT USE OF TABLESPACE USERS TO USER <DBUSER>;
GRANT USE OF TABLESPACE INDX TO USER <DBUSER>;
GRANT USE OF TABLESPACE BLOB_TBL_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE TEMP_USER TO USER <DBUSER>;
GRANT USE OF TABLESPACE XML_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE XML_LARGE_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE XML_INDEX TO USER <DBUSER>;

GRANT USE OF TABLESPACE ICM_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE ICM_IX TO USER <DBUSER>;
GRANT USE OF TABLESPACE ITM_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE ITM_IX TO USER <DBUSER>;
GRANT USE OF TABLESPACE ITD_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE ITD_IX TO USER <DBUSER>;
GRANT USE OF TABLESPACE ITA_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE ITA_IX TO USER <DBUSER>;
GRANT USE OF TABLESPACE LCK_DATA TO USER <DBUSER>;
GRANT USE OF TABLESPACE LCK_IX TO USER <DBUSER>;
